services:
  app-redis:
    restart: always
    image: redis:alpine
    container_name: ${GHOST_REDIS_HOSTNAME}
    ports:
      - "6379:6379"
  app-db:
    restart: always
    image: postgres:alpine
    container_name: ${POSTGRES_HOSTNAME}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - app-data:${PGDATA}
  app-web:
    restart: always
    image: ${CI_REGISTRY_IMAGE}/app-django:${CI_IMAGE_TAG}
    container_name: ${GHOST_APP_WEB_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: django-app.Dockerfile
    volumes:
      - static-data:${GHOST_STATIC_FILES_FOLDER}
      - media-data:${GHOST_MEDIA_FILES_FOLDER}
    ports:
      - "${GHOST_WEB_APP_PORT}:5000"
    depends_on:
      - app-db
  app-celery:
    restart: always
    image: ${CI_REGISTRY_IMAGE}/app-django:${CI_IMAGE_TAG}
    container_name: ${GHOST_APP_CELERY_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: django-app.Dockerfile
    volumes:
      - media-data:${GHOST_MEDIA_FILES_FOLDER}
    command: ["celery", "-A", "ghost_base_folder", "worker", "-l", "info"]
    depends_on:
      - app-db
      - app-redis
      - app-web
  app-celery-beat:
    restart: always
    image: ${CI_REGISTRY_IMAGE}/app-django:${CI_IMAGE_TAG}
    container_name: ${GHOST_APP_CELERY_BEAT_NAME}
    build:
      context: .
      dockerfile: django-app.Dockerfile
    env_file:
      - .dev.env
    volumes:
      - media-data:${GHOST_MEDIA_FILES_FOLDER}
    command: [ "celery", "-A", "ghost_base_folder", "beat", "-l", "info" ]
    depends_on:
      - app-web
      - app-db
      - app-redis
  app-nginx:
    restart: always
    image: ${CI_REGISTRY_IMAGE}/app-nginx:${CI_IMAGE_TAG}
    container_name: ${GHOST_APP_NGINX_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    volumes:
      - static-data:/vol/static
      - media-data:/vol/media
    ports:
      - "${GHOST_NGINX_PORT}:80"
      - "${GHOST_NGINX_HTTPS_PORT}:443"
    depends_on:
      - app-web

volumes:
  app-data:
  static-data:
  media-data:
