# Generated by Django 4.1.1 on 2022-11-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_signintoken_create_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signintoken',
            options={'ordering': ['-create_datetime']},
        ),
    ]
