# Generated by Django 4.1.1 on 2022-09-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='')),
                ('text', models.TextField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_edit', '-create_datetime'],
            },
        ),
    ]
