# Generated by Django 4.1.1 on 2022-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0004_transcription_audio_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='audio_duration',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
