# Generated by Django 4.1.1 on 2022-10-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0005_alter_transcription_audio_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='audio_duration',
            new_name='duration',
        ),
    ]
