# Generated by Django 4.1.1 on 2022-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0009_transcription_is_mp3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
