# Generated by Django 4.1.1 on 2022-10-26 21:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0010_alter_transcription_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
